# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller recipe for a TRUE single-file Windows executable.

Build:
    pyinstaller --clean --noconfirm windows_onefile.spec

Result:
    dist/JeongSoyoonAI.exe

All application code, Python dependencies, Streamlit frontend assets, and the
bundled Playwright Chromium directory are embedded into this one EXE.
At runtime PyInstaller extracts them to its temporary _MEIPASS directory.
The application's writable data remains in %LOCALAPPDATA%\JeongSoyoonAI,
as configured by main.py.
"""

from pathlib import Path

from PyInstaller.utils.hooks import (
    collect_all,
    collect_submodules,
    get_module_file_attribute,
)

ROOT = Path(SPECPATH)

datas = []
binaries = []
hiddenimports = []

# ---------------------------------------------------------------------------
# Keep every dependency used by the existing application.
# collect_all() preserves package data, binaries and hidden imports that
# PyInstaller's normal import analysis may miss.
# ---------------------------------------------------------------------------
PACKAGES = (
    "streamlit",
    "playwright",
    "langchain",
    "langchain_community",
    "langchain_core",
    "langchain_experimental",
    "langchain_openai",
    "langchain_text_splitters",
    "langchain_chroma",
    "langgraph",
    "chromadb",
    "faiss",
    "numpy",
    "pandas",
    "pydantic",
    "requests",
    "numexpr",
    "mypy_extensions",
)

for package in PACKAGES:
    try:
        package_datas, package_binaries, package_hiddenimports = collect_all(package)
        datas += package_datas
        binaries += package_binaries
        hiddenimports += package_hiddenimports
    except Exception as exc:
        print(f"[spec] collect_all skipped {package!r}: {exc}")

# A few namespace/dynamic-import heavy packages are explicitly collected.
for package in (
    "langchain_community",
    "langchain_experimental",
    "langchain_openai",
    "langchain_text_splitters",
    "langchain_chroma",
    "langgraph",
    "chromadb",
    "playwright",
):
    try:
        hiddenimports += collect_submodules(package)
    except Exception as exc:
        print(f"[spec] collect_submodules skipped {package!r}: {exc}")

# ---------------------------------------------------------------------------
# Application source
# ---------------------------------------------------------------------------
datas.append((str(ROOT / "main.py"), "."))

# The voice component is generated by main.py into the writable runtime
# directory, but keeping the original source copy in the EXE also preserves
# the project exactly as supplied.
voice_dir = ROOT / "_live_voice_component"
if voice_dir.is_dir():
    datas.append((str(voice_dir), "_live_voice_component"))

# ---------------------------------------------------------------------------
# Streamlit frontend assets
# ---------------------------------------------------------------------------
streamlit_package_dir = Path(get_module_file_attribute("streamlit")).parent
streamlit_static_dir = streamlit_package_dir / "static"
streamlit_index = streamlit_static_dir / "index.html"

if not streamlit_index.is_file():
    raise SystemExit(
        f"Streamlit UI assets were not found: {streamlit_index}"
    )

# Preserve the exact path expected by app.py:
#   _MEIPASS/streamlit/static/index.html
datas.append((str(streamlit_static_dir), "streamlit/static"))

# ---------------------------------------------------------------------------
# Playwright browsers
# ---------------------------------------------------------------------------
browser_dir = ROOT / "playwright-browsers"
if not browser_dir.is_dir():
    raise SystemExit(
        "Missing playwright-browsers; run "
        "'playwright install chromium' before building."
    )

datas.append((str(browser_dir), "playwright-browsers"))

# ---------------------------------------------------------------------------
# Build analysis
# ---------------------------------------------------------------------------
a = Analysis(
    [str(ROOT / "app.py")],
    pathex=[str(ROOT)],
    binaries=binaries,
    datas=datas,
    hiddenimports=sorted(set(hiddenimports)),
    noarchive=False,
)

pyz = PYZ(a.pure)

# ---------------------------------------------------------------------------
# TRUE ONE-FILE EXE
#
# Do NOT use COLLECT here.  COLLECT creates the old one-folder distribution.
# exclude_binaries=False embeds all binaries/data into this EXE.
# ---------------------------------------------------------------------------
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="JeongSoyoonAI",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

# Intentionally no COLLECT().
